name: Rust

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Create artifacts directory
      run: mkdir artifacts
    - name: Add MUSL target (x86_64)
      run: rustup target add x86_64-unknown-linux-musl
    - name: Build Static (x86_64)
      run: |
        cargo build --release --target x86_64-unknown-linux-musl --verbose
        cp target/x86_64-unknown-linux-musl/release/avcscope ./artifacts/avcscope-static
    - name: Build Standard (x86_64)
      run: |
        cargo build --release
        cp target/release/avcscope ./artifacts/avcscope
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@v7.0.1
      with: 
        name: All artifacts
        path: artifacts/*
